### ISSUE TITLE
android.widget.ImageView cannot be cast to android.view.ViewGroup (CustomViewPager.java:33)

### ISSUE THREAD

**Issue by jaimeagudo** [saeedsh92/Banner-Slider#11]
Just setting up a banner-slider with a few ImageViews loaded with Picasso and I get: 

Relevant exception trace:
```
Fatal Exception: java.lang.ClassCastException
android.widget.ImageView cannot be cast to android.view.ViewGroup
 Raw Text
android.support.v4.app.FragmentTransition.configureTransitionsUnoptimized (FragmentTransition.java:284)
android.support.v4.view.ViewPager.onMeasure (ViewPager.java:1642)
ss.com.bannerslider.views.CustomViewPager.onMeasure (CustomViewPager.java:33)
```
Any clues?

Full Stacktrace
```
Fatal Exception: java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup
       at android.support.v4.app.FragmentTransition.configureTransitionsUnoptimized(FragmentTransition.java:284)
       at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:113)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2143)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1979)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
       at ss.com.bannerslider.views.CustomViewPager.onMeasure(CustomViewPager.java:33)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
       at android.view.View.measure(View.java:18805)
       at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:18805)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
       at android.view.View.measure(View.java:18805)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by saeedsh92** [comment]
i don't have any cast to ViewGroup in CustomViewPager class, are you change anything there?

**Comment by mori-honest** [comment]
can you add the code you implemented?

**Comment by TacB0sS** [comment]
any known reason for this guys?

**Comment by azizainunnajib** [comment]
is this happen in kotlin? i change my code to kotlin and this happen. but before i change my code, as i remember everything is fine.

**Comment by azizainunnajib** [comment]
do you find the problem? i change my BannerSlider to activity. and everything work correctly. i used fragment and here the problem was coming.

**Comment by mat8854** [comment]
We had the same problem with FragmentStatePagerAdapter inside Fragments.

If you use Fragments of any kind in Fragments you have to use **getChildFragmentManager()** instead of **getFragmentManager()** from Fragment class to setup your views.

That solved the issuse for us.

**Comment by jahongir9779** [comment]
any solutions for this? The same bug, also in kotlin didn't try in java

**Comment by jahongir9779** [comment]
it happens when you setLoopSlides(true) and setInterval(*) when u have banners size of 1 or zero, i solved it with 
  if    (squareBanners.size > 1){
                          banner_slider.setLoopSlides(true)
                        banner_slider.setInterval(5000)
                      }
