### ISSUE TITLE
ArrayIndexOutOfBoundsException after update items

### ISSUE THREAD

**Issue by mehdi-salehi** [saeedsh92/Banner-Slider#112]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-2
       at java.util.ArrayList.get(ArrayList.java:439)
       at o.mainactivity.onSlideClick(SourceFile:115)
       at o.send.onClick(SourceFile:70)
       at android.view.View.performClick(View.java:7341)
       at android.view.View.performClickInternal(View.java:7307)
       at android.view.View.access$3200(View.java:846)
       at android.view.View$PerformClick.run(View.java:27796)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by josequintana94** [comment]
Same here, any solution?

**Comment by josequintana94** [comment]
this also happens when I only have one element in the slider and I try to click and it runs setOnSlideClickListener
