### ISSUE TITLE
Host activity must extend AppCompatActivity

### ISSUE THREAD

**Issue by Frankenstein666** [saeedsh92/Banner-Slider#15]
I am receiving following error:
**java.lang.RuntimeException: Host activity must extend AppCompatActivity**
i'm sure my activity extends AppCompatActivity.

**Comment by deep1931** [comment]
how you found the solution because i am facing the same issue..
java.lang.RuntimeException: Host activity must extend AppCompatActivity
                                                              at ss.com.bannerslider.views.BannerSlider$1.run(BannerSlider.java:124)
                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6153)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by KingIdee** [comment]
Experienced same issue. And I need this feature in a production app by tomorrow. Any help, or any other library suggestion ?

**Comment by deep1931** [comment]
I have fixed this issue but not remember now how i did. but you can use this library
https://github.com/daimajia/AndroidImageSlider

**Comment by zzzzzzzzoli** [comment]
In my case the problem was that the library expects the context to be AppCompatActivity (which my activity is) but getContext() returns ContextWrapper. 
So I imported the library and changed its code starting at line 123 of BannerSlider.java to this:
```
if (getContext() instanceof AppCompatActivity) {
                        hostActivity = (AppCompatActivity) getContext();
                    } else if (getContext() instanceof ContextWrapper && ((ContextWrapper) getContext()).getBaseContext() instanceof AppCompatActivity) {
                        hostActivity = (AppCompatActivity)((ContextWrapper)getContext()).getBaseContext();
                    } else {
                        throw new RuntimeException("Host activity must extend AppCompatActivity");
                    }
```

Also, when I added no indicators the library crashed, that was solved by changing
```
slideIndicatorsGroup.onSlideAdd();
```
to
```
if (!hideIndicators) {
    slideIndicatorsGroup.onSlideAdd();
}
```
in method setBanners of BannerSlider.java

**Comment by hassaanjamil** [comment]
I am facing the same issue as @Frankenstein666 is facing, any help will be appreciated.

**Comment by deep1931** [comment]
I need to check what patch i had applied because i used this lib long time
ago

**Comment by saeedsh92** [comment]
The host activity of this library must extend the AppCompatActivity
