### ISSUE TITLE
Problem with Image in Fragment

### ISSUE THREAD

**Issue by kevega** [saeedsh92/Banner-Slider#16]
Hi, In an activity does not fail the application, But in a fragment with the same image it fails.
I leave my code.

public class FragmentTabsMenuTienda extends Fragment {

    View rootView;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.fragment_inicio_main_tips, container, false);
        return rootView;
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        setRetainInstance(false);

        BannerSlider bannerSlider = (BannerSlider)rootView.findViewById(R.id.banner_slider1);
        //bannerSlider.addBanner(new RemoteBanner("http://mt5.tuvotacion.com:81/imagenes_unicas/cual-perrito-es-mas-tierno-450089.jpg"));
        //bannerSlider.addBanner(new DrawableBanner(R.drawable.fondo1));
        bannerSlider.addBanner(new DrawableBanner(R.drawable.preview));

        bannerSlider.setOnBannerClickListener(new OnBannerClickListener() {
            @Override
            public void onClick(int position) {
                Toast.makeText(getActivity(), "Banner with position " + String.valueOf(position) + " clicked!", Toast.LENGTH_SHORT).show();
            }
        });

    }

**Comment by saeedsh92** [comment]
Send me your error full stacktrace

**Comment by flamenvo** [comment]
I also encountered the same problem

**Comment by flamenvo** [comment]
parseCustomAttributes:

**Comment by surveshoeb** [comment]
Same issue
` FATAL EXCEPTION: main
                                                             Process: com.spiritz, PID: 13114
                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'void ss.com.bannerslider.views.BannerAdapter.addBanner(ss.com.bannerslider.banners.Banner)' on a null object reference
                                                                 at ss.com.bannerslider.views.BannerSlider$2.run(BannerSlider.java:151)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:179)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5730)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)`

**Comment by RadoVidjenGost** [comment]
I got the same problem, can you please help?

**Comment by SethAlilio** [comment]
Your bannerSlider does not have an adapter attached to it
