### ISSUE TITLE
 No view found for id 0x3 (unknown) for fragment BannerFragment

### ISSUE THREAD

**Issue by paveltech** [saeedsh92/Banner-Slider#26]
I am using this banner into a fragment. First it works great but when i open my sliding menu and go another fragment and come back again it shows error 
java.lang.IllegalArgumentException: No view found for id 0x3 (unknown) for fragment BannerFragment{6f4a71d #12 id=0x3}

any one facing this issue??

**Comment by paveltech** [comment]
It shows this error 

  Process: com.playoffstudio.hindimoviesandVideoSongs, PID: 8620
                                                                                          java.lang.IllegalArgumentException: No view found for id 0x4 (unknown) for fragment BannerFragment{a8508a8 #15 id=0x4}
                                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1293)
                                                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                              at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                              at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                              at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                              at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                              at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                                              at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                                              at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                                                              at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                              at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
                                                                                              at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                                              at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                                              at ss.com.bannerslider.views.BannerSlider$5$1.run(BannerSlider.java:279)
                                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by hvardhan878** [comment]
I have the same problem. Did you find the solution?

**Comment by paveltech** [comment]
No i don't and waiting for answer..

**Comment by ratanakpek** [comment]
I have this problem too, who can help?

**Comment by ratanakpek** [comment]
I found this problem! The problem is "Nested fragment" problem. 
Ex: You have your own fragment and then each slider of Banner Slider library is also fragment. 

I checked in BannerSlider.class, I found this:

 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                bannerAdapter = new BannerAdapter(hostActivity.getSupportFragmentManager(), mustLoopSlides, getLayoutDirection(), banners);
            } else {
                bannerAdapter = new BannerAdapter(hostActivity.getSupportFragmentManager(), mustLoopSlides, banners);
            }


*Solution: You should change to this:
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                bannerAdapter = new BannerAdapter(hostFragment.getChildFragmentManager(), mustLoopSlides, getLayoutDirection(), banners);
            } else {
                bannerAdapter = new BannerAdapter(hostFragment.getChildFragmentManager(), mustLoopSlides, banners);
            }

**Comment by Vinayak2108** [comment]
@ratanakpek  How you made this changes bcoz hostActivity instance is obtained from getContext(). but how we can get hostFragment? also if we are using it in two place in app one time in activity and second time in fragment then how it will handle it?

**Comment by pushpendra996** [comment]
I am also facing this problem, Some time it's working fine but some time it show this error. Please resolve this problem.
