### ISSUE TITLE
Hide Indicators does not work

### ISSUE THREAD

**Issue by eminsr** [saeedsh92/Banner-Slider#35]
Hi there nice library but I encounter this problem. When I add app:hideIndicators="true" to the view or use if I use bannerSlider.setHideIndicators(true); the app crashes.

`java.lang.NullPointerException
                                                                          at ss.com.bannerslider.views.BannerSlider.setBanners(BannerSlider.java:188)
                                                                          at ss.com.bannerslider.views.BannerSlider.renderRemainingBanners(BannerSlider.java:207)
                                                                          at ss.com.bannerslider.views.BannerSlider.access$1100(BannerSlider.java:37)
                                                                          at ss.com.bannerslider.views.BannerSlider$1.run(BannerSlider.java:147)
                                                                          at android.os.Handler.handleCallback(Handler.java:730)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                          at dalvik.system.NativeStart.main(Native Method)`

**Comment by bartarapp** [comment]
I also have a problem
Meanwhile, when it receives a picture from the server, it shows the Indicators more than reality

**Comment by robmaas** [comment]
A little delay is a workaround for this problem:

`new Handler().postDelayed(new Runnable() {
    @Override
    public void run() {
            slider.setHideIndicators(true);
     }
}, 100);`
