### ISSUE TITLE
Error in picasso on update picaso picasso:2.71828

### ISSUE THREAD

**Issue by ridho2311** [saeedsh92/Banner-Slider#60]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: kawan.gitsolution.kawan, PID: 24707
                  java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/kawan.gitsolution.kawan-2/base.apk:classes2.dex)
                      at ss.com.bannerslider.views.fragments.BannerFragment.onCreateView(BannerFragment.java:54)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                      at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                      at ss.com.bannerslider.views.CustomViewPager.onMeasure(CustomViewPager.java:32)
                      at android.view.View.measure(View.java:18811)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.view.View.measure(View.java:18811)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                      at android.view.View.measure(View.java:18811)
                      at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1283)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.widget.ScrollView.onMeasure(ScrollView.java:340)
                      at android.view.View.measure(View.java:18811)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                      at android.view.View.measure(View.java:18811)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                      at android.view.View.measure(View.java:18811)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                      at android.view.View.measure(View.java:18811)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                      at android.view.View.measure(View.java:18811)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                      at android.view.View.measure(View.java:18811)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)

Picasso.with(getActivity()) to Picasso.get()

**Comment by saeedsh92** [comment]
hi, plz use the latest version, in v2 you can use your favorite image loading service
