### ISSUE TITLE
ImageLoadingService is null, you should call init method first

### ISSUE THREAD

**Issue by yogiwisesa** [saeedsh92/Banner-Slider#61]
I got this error while using the 2.0 version, I've already created the adapter and image loading service class that implements ImageLoadingService.

` java.lang.IllegalStateException: ImageLoadingService is null, you should call init method first
        at ss.com.bannerslider.Slider.getImageLoadingService(Slider.java:279)
        at ss.com.bannerslider.viewholder.ImageSlideViewHolder.bindImageSlide(ImageSlideViewHolder.java:25)
        at com.yogiw.canika.Adapter.BannerAdapter.onBindImageSlide(BannerAdapter.java:27)`

Thank you

**Comment by thelastsummer** [comment]
add this code on your activty
Slider.init(new PicassoImageLoadingService(this));

**Comment by Amghoughg** [comment]
add this code on your activty
slider.setAdapter( new MainSliderAdapter() );
