### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by yusufaw** [saeedsh92/Banner-Slider#70]
Process: com.passpod.dev, PID: 26564
    java.lang.NullPointerException: Attempt to invoke virtual method 'int ss.com.bannerslider.adapters.PositionController.getNextSlide(int)' on a null object reference
        at ss.com.bannerslider.Slider$SliderTimerTask$1.run(Slider.java:291)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

**Comment by devang-p-eq** [comment]
I am also get this error
I have added interval and also delay for this call
and still crash when page load
Attempt to invoke virtual method 'int ss.com.bannerslider.adapters.PositionController.getNextSlide(int)' on a null object reference
