### ISSUE TITLE
Got crash issue on load page

### ISSUE THREAD

**Issue by PinkalBaleshwaria** [saeedsh92/Banner-Slider#92]
Got crash issue on load page

 java.lang.NullPointerException: Attempt to invoke virtual method 'int ss.com.bannerslider.adapters.PositionController.getNextSlide(int)' on a null object reference
        at ss.com.bannerslider.Slider$SliderTimerTask$1.run(Slider.java:291)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by AyushiBShah** [comment]
+1

**Comment by subrud** [comment]
Yes, I am also getting this error

**Comment by subrud** [comment]
i got the solution here https://github.com/saeedsh92/Banner-Slider/issues/92

**Comment by devang-p-eq** [comment]
I am also getting this error!! any solution
Attempt to invoke virtual method 'int ss.com.bannerslider.adapters.PositionController.getNextSlide(int)' on a null object reference

**Comment by TheLightMoon** [comment]
Me too. Look like top
